server:
  port: 8181

spring:
  datasource:
    url: jdbc:h2:mem:test-db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


  application:
    name: GATEWAY-SERVICE

  config:
    import: "optional:configserver:http://localhost:9196"

  cloud:
    gateway:
      routes:
        - id: order-service # as a list
          uri: lb://ORDER-SERVICE #loadbalancer service name
          predicates:
            - Path=/order/** #url pattern any path starting with/order will redirect to order service if failure send to orderFallBack which is configured in FallBackController
          filters:
          - name: CircuitBreaker
            args:
              name: orderServiceCB
              fallbackUri: forward:/orderFallBack

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
              - Path=/payment/** #url pattern any path starting with/payment will redirect to payment service if failure send to paymentFallBack which is configured in FallBackController
          filters:
              - name: CircuitBreaker
                args:
                  name: paymentServiceCB
                  fallbackUri: forward:/paymentFallBack

        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/inventory/** #url pattern any path starting with/payment will redirect to payment service if failure send to paymentFallBack which is configured in FallBackController
          filters:
            - name: CircuitBreaker
              args:
                name: inventoryServiceCB
                fallbackUri: forward:/inventoryFallBack
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost

logging:
  level:
    org.springframework.cloud.gateway: TRACE

#exposes actuator endpoints like health and circuit breaker status so we can monitor application behavior in bruno/browser.
management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers

#giving timeout of 5 s if request is not giving anything in 5s redirect to fallback

resilience4j:
  timelimiter:
    instances:
      orderServiceCB:
        timeoutDuration: 5s
      paymentServiceCB:
        timeoutDuration: 5s
      inventoryServiceCB:
        timeoutDuration: 5s


#Request → Gateway → Order Service
#                 ↓ (no response for 5 sec)
#         TimeLimiter triggers ⏱️
#                 ↓
#         CircuitBreaker fallback

  #Circuit breaker at gateway handles external failures,
  #but for inter-service communication we must also implement circuit breaker at service level.