server:
  port: 9191

spring:
  datasource:
    url: jdbc:h2:mem:test-db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


  application:
      name: PAYMENT-SERVICE

  config:
    import: "optional:configserver:http://localhost:9196" #talking to config server applciation this used to be in bootstrap.yml which loads before application.yml new way is this

  cloud:
    config:
      profile: default  #talking to config server applciation


management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents

  endpoint:
    health:
      show-details: always

logging:
  file:
    name: C:/Users/ASUS/Desktop/logs/microservice.log
