spring.application.name=user-service
spring.session.store.type=jdbc
spring.session.jdbc.initialise-schema=always
server.servlet.session.timeout=5m

#by default path is /actuator
management.endpoints.web.base-path=/manage

# * ->Expose all actuator endpoints by default '/actuator/health' & '/actuator/info' endpoint is exposed , use comma seperated like : health, info, metrics, loggers etc. to expose selected endpoints
management.endpoints.web.exposure.include=*

#never -> bare status only (the default), when-authorized -> full details only if the requester has an authorized role (needs management.endpoint.health.roles=ADMIN or similar configured too)
management.endpoint.health.show-details=always

#Make it require authentication for /shutdown(can stop app) & /heapdump(can expose sensitive information abt your applike tokens/pwd) need to write manually unrestricted then only can access it
management.endpoint.heapdump.access = unrestricted
management.endpoint.shutdown.access = unrestricted

#creating a user in mem at application startup itself
spring.security.user.name=user
spring.security.user.password=pass
spring.security.user.roles=ADMIN


#when its true then try to push the metrics into datadog
#management.datadog.metrics.export.enabled=true
#management.datadog.metrics.export.api-key=YOUR_DATADOG_API_KEY
#in which frequency springboot pushes the metrics to datadog
#management.datadog.metrics.export.step=5s

#ConfigurationProperties
app.user.name=test_user
app.user.age=27
app.user.active=true
app.user.address.city=myCityName
app.user.address.country=myCountryName

#List<String>
app.user.roles[0]=ADMIN
app.user.roles[1]=EDITOR

#List<Object>
app.user.course[0].name=Java
app.user.course[0].enrolled=true

app.user.course[1].name=Springboot
app.user.course[1].enrolled=false

#Map<String, String> preferences
app.user.preferences.theme=dark
app.user.preferences.language=en
app.user.preferences.timezone=IST

#Map<String, Address>
#home -> {city=Jaipur, state=Rajasthan}
#office->{city=Delhi, state=Delhi}
app.user.locations.home.city=Jaipur
app.user.locations.home.country=India

app.user.locations.office.city=Delhi
app.user.locations.office.country=India


# =========================================
# GITLAB OAUTH2 CLIENT
# =========================================
spring.security.oauth2.client.registration.gitlab.client-id=f3983b182f51cb59351b46089b1128f516b95ff6db4f24f821826308ef05c96a
spring.security.oauth2.client.registration.gitlab.client-secret=gloas-cb71ffe0c160652c8ad6355929a5ebd9738cfe29282aa43c2ae11ef7d707b701
spring.security.oauth2.client.registration.gitlab.scope=openid
spring.security.oauth2.client.registration.gitlab.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.gitlab.redirect-uri=http://localhost:9195/login/oauth2/code/gitlab
spring.security.oauth2.client.registration.gitlab.client-name=GitLab

spring.security.oauth2.client.provider.gitlab.authorization-uri=https://gitlab.com/oauth/authorize
spring.security.oauth2.client.provider.gitlab.token-uri=https://gitlab.com/oauth/token
spring.security.oauth2.client.provider.gitlab.user-info-uri=https://gitlab.com/api/v4/user
spring.security.oauth2.client.provider.gitlab.user-name-attribute=sub
spring.security.oauth2.client.provider.gitlab.jwk-set-uri=https://gitlab.com/oauth/discovery/keys
spring.security.oauth2.client.provider.gitlab.issuer-uri=https://gitlab.com

# =========================================
# AUTH0 OAUTH2 CLIENT
# =========================================
spring.security.oauth2.client.registration.auth0.client-id=k9uBP2yM3NKJO7MYowBYrSJqldCTAZ77
spring.security.oauth2.client.registration.auth0.client-secret=R6936POThN0BuAikzSMc5pmYo9Utio_7xVr8lhHmVZAMrzNPMCKZWwWx2MLbm9DJ
spring.security.oauth2.client.registration.auth0.scope=openid,profile,email
spring.security.oauth2.client.registration.auth0.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.auth0.redirect-uri=http://localhost:9195/login/oauth2/code/auth0
spring.security.oauth2.client.registration.auth0.client-name=Auth0

spring.security.oauth2.client.provider.auth0.issuer-uri=https://dev-3liygg05bbrubq1f.us.auth0.com/
spring.security.oauth2.client.provider.auth0.authorization-uri=https://dev-3liygg05bbrubq1f.us.auth0.com/authorize
spring.security.oauth2.client.provider.auth0.token-uri=https://dev-3liygg05bbrubq1f.us.auth0.com/oauth/token
spring.security.oauth2.client.provider.auth0.user-info-uri=https://dev-3liygg05bbrubq1f.us.auth0.com/userinfo
spring.security.oauth2.client.provider.auth0.jwk-set-uri=https://dev-3liygg05bbrubq1f.us.auth0.com/.well-known/jwks.json
spring.security.oauth2.client.provider.auth0.user-name-attribute=sub