server:
  port: 9192

spring:
  datasource:
    url: jdbc:h2:mem:test-db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: ORDER-SERVICE

  config:
    import: "optional:configserver:http://localhost:9196" #talking to config server applciation this used to be in bootstrap.yml which loads before application.yml new way is this

  cloud:
    config:
      profile: default


management:
  tracing:
    enabled: false # remove this when u want to trace in zipkin
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents

  endpoint:
    health:
      show-details: always

logging:
  file:
    name: C:/Users/ASUS/Desktop/logs/microservice.log


resilience4j:
  circuitbreaker:
    instances:
      paymentService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10

        # If 50% of requests fail, circuit opens
        failureRateThreshold: 50

        # Minimum calls before calculating failure rate
        minimumNumberOfCalls: 5

        # Automatically move OPEN -> HALF_OPEN after wait time
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s

        # Number of trial calls allowed in HALF_OPEN state
        permittedNumberOfCallsInHalfOpenState: 3

        # Sliding window type: COUNT_BASED or TIME_BASED
        slidingWindowType: COUNT_BASED

        # Last 10 requests considered
        slidingWindowSize: 10

  retry:
    instances:
      inventoryService:
        #(max no of attempt from order service to inventory service in each 5s once)
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2